version: '3'

services:
  db-test:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      test:
      
  credential-schema-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db-test:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db-test:5432/postgres
      IDENTITY_BASE_URL: "http://identity-service:3332"
      ENABLE_AUTH: "false"
    networks:
      rcw-test:

networks:
  test: